- name: Run Windows command dynamically
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute command on Windows server
      win_shell: "hostname"
      delegate_to: "{{ target_host }}"
      vars:
        ansible_user: Ansibleuser
        ansible_password: Aug@123
        ansible_host: "{{ target_host }}"
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic
